name: simplyfirescore
description: "SimplyFires Base"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router:
  bloc:
  freezed:
  build_runner:
  dartz:
  json_serializable:
  logger:
  json_annotation:
  freezed_annotation:
  equatable: 
  mockito: 
  test: 
  data_table_2: 
  dio: 
  get_it:
  get:
  easy_localization:
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  cloud_functions: ^5.3.0
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/