name: simplyfirescore
description: "SimplyFires Base"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  cloud_functions: ^5.3.0
  firebase_messaging: ^15.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  data_table_2: ^2.5.18
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  go_router: ^14.6.3
  get: ^4.6.6
  dio: ^5.7.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.2

  
  

flutter:
  uses-material-design: true
  assets:
    - assets/